#!/usr/bin/env bash
set -e
# Install composer dependencies
docker run --rm -v $(pwd):/app composer install
# Create .env from .env.example
cp .env.example .env
# Add hosts
if [[ -w /etc/hosts ]]; then
    use_sudo=
else
    use_sudo='sudo'
fi
# check the hostname and only add entries if they are not already in the file
if ! grep -q 'backend.growthops.localdomain' '/etc/hosts'; then
    echo '' | $use_sudo tee -a /etc/hosts > /dev/null
    echo '127.0.0.1 backend.growthops.localdomain' | $use_sudo tee -a /etc/hosts > /dev/null
fi
# Start containers
docker-compose up -d
# Generate key
docker-compose exec backend php artisan key:generate
# Optimize
docker-compose exec backend php artisan optimize
# Seed data
docker-compose exec backend php artisan db:seed --class=PlantTableSeeder
